### ISSUE TITLE
after your facebook add I seem to be getting stuck on pin wheel

### ISSUE THREAD

**Issue by Cubler** [rrogowski/boulder-buddy#16]

**Comment by Cubler** [comment]
![screenshot from 2017-09-09 10-37-40](https://user-images.githubusercontent.com/10574856/30241119-325b3d2a-954b-11e7-955e-693b71d84ebc.png)
![screenshot from 2017-09-09 10-38-12](https://user-images.githubusercontent.com/10574856/30241118-325a7ae8-954b-11e7-83b0-97129a1303a8.png)

**Comment by rrogowski** [comment]
Facebook app was still in developer mode. Now, it is public.
